In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
df = pd.read_csv("/Churn_Modelling.csv")

In [39]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [43]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [44]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [45]:
df.drop(columns=["RowNumber", "CustomerId", "Surname"], inplace=True)

In [46]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [47]:
df = pd.get_dummies(df,columns=["Gender", "Geography"], drop_first=True)

In [48]:
from sklearn.model_selection import train_test_split
x = df.drop(columns=["Exited"])
y = df["Exited"]
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1  )

In [49]:
x_train.shape

(8000, 11)

In [50]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [51]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [52]:
  model = Sequential()
  model.add(Dense(32, activation="relu", input_dim=11))
  model.add(Dense(16, activation="relu"))
  model.add(Dense(1, activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [53]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 32)             │           384 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 929 (3.63 KB)

 Trainable params: 929 (3.63 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.compile(loss="binary_crossentropy", optimizer="Adam", metrics=["accuracy"])

In [55]:
model.fit(x_train_scaled, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7788 - loss: 0.5024 - val_accuracy: 0.8131 - val_loss: 0.4415
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8220 - loss: 0.4225 - val_accuracy: 0.8300 - val_loss: 0.4093
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8350 - loss: 0.3973 - val_accuracy: 0.8363 - val_loss: 0.3869
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8428 - loss: 0.3774 - val_accuracy: 0.8450 - val_loss: 0.3701
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8531 - loss: 0.3583 - val_accuracy: 0.8450 - val_loss: 0.3614
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8591 - loss: 0.3475 - val_accuracy: 0.8512 - val_loss: 0.3501
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8598 - loss: 0.3421 - val_accuracy: 0.8512 - val_loss: 0.3528
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8648 - loss: 0.3381 - val_accuracy: 0.8506 - val_loss: 0.3499
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8644 - loss: 0.3368 - val_accuracy: 0.8525 - val_loss: 0.3477
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8647 - loss: 0.3328 - val_accuracy: 0.8531 - val_loss: 0.3470
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8650 - loss: 0.3315 - val_accuracy: 0.8525 - val_loss: 0.3503
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8664 - loss: 0.3291 - val_accuracy: 0.8456 - val_loss: 0.3508
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8675 - loss: 0.3280 - val_accuracy: 0.8481 - val_loss: 0.3510
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8661 - loss: 0.3270 - val_accuracy: 0.8481 - val_loss: 0.3461
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8647 - loss: 0.3253 - val_accuracy: 0.8506 - val_loss: 0.3493
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8666 - loss: 0.3245 - val_accuracy: 0.8531 - val_loss: 0.3458
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8664 - loss: 0.3233 - val_accuracy: 0.8512 - val_loss: 0.3465
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3222 - val_accuracy: 0.8531 - val_loss: 0.3457
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3215 - val_accuracy: 0.8494 - val_loss: 0.3456
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3202 - val_accuracy: 0.8500 - val_loss: 0.3452
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8698 - loss: 0.3194 - val_accuracy: 0.8525 - val_loss: 0.3463
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8686 - loss: 0.3183 - val_accuracy: 0.8494 - val_loss: 0.3487
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8711 - loss: 0.3177 - val_accuracy: 0.8519 - val_loss: 0.3469
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8717 - loss: 0.3170 - val_accuracy: 0.8525 - val_loss: 0.3439
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8706 - loss: 0.3163 - val_accuracy: 0.8487 - val_loss: 0.3482
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8708 - loss: 0.3159 - val_accuracy: 0.8506 - val_loss: 0.3453
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8705 - loss: 0.3148 - val_accuracy: 0.8500 - val_loss: 0.3473
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8720 - loss: 0.3141 - val_accuracy: 0.8481 - val_loss: 0.3491
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8709 - loss: 0.3144 - val_accuracy: 0.8525 - val_loss: 0.3478
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8720 - loss: 0.3136 - val_accuracy: 0.8481 - val_loss: 0.3483
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8702 - loss: 0.3128 - val_accuracy: 0.8475 - val_loss: 0.3526
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8717 - loss: 0.3118 - val_accuracy: 0.8500 - val_loss: 0.3481
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8714 - loss: 0.3113 - val_accuracy: 0.8487 - val_loss: 0.3500
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8716 - loss: 0.3115 - val_accuracy: 0.8469 - val_loss: 0.3480
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8727 - loss: 0.3111 - val_accuracy: 0.8481 - val_loss: 0.3498
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8758 - loss: 0.3102 - val_accuracy: 0.8494 - val_loss: 0.3528
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8719 - loss: 0.3090 - val_accuracy: 0.8537 - val_loss: 0.3465
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8708 - loss: 0.3089 - val_accuracy: 0.8500 - val_loss: 0.3491
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8733 - loss: 0.3080 - val_accuracy: 0.8506 - val_loss: 0.3502
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8727 - loss: 0.3083 - val_accuracy: 0.8531 - val_loss: 0.3498
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8730 - loss: 0.3077 - val_accuracy: 0.8494 - val_loss: 0.3519
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8745 - loss: 0.3065 - val_accuracy: 0.8469 - val_loss: 0.3561
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8727 - loss: 0.3069 - val_accuracy: 0.8469 - val_loss: 0.3514
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8734 - loss: 0.3065 - val_accuracy: 0.8494 - val_loss: 0.3514
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8750 - loss: 0.3049 - val_accuracy: 0.8487 - val_loss: 0.3539
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8748 - loss: 0.3051 - val_accuracy: 0.8481 - val_loss: 0.3502
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8752 - loss: 0.3045 - val_accuracy: 0.8494 - val_loss: 0.3555
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8778 - loss: 0.3043 - val_accuracy: 0.8481 - val_loss: 0.3542
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8744 - loss: 0.3038 - val_accuracy: 0.8487 - val_loss: 0.3523
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8753 - loss: 0.3032 - val_accuracy: 0.8462 - val_loss: 0.3560
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8755 - loss: 0.3028 - val_accuracy: 0.8487 - val_loss: 0.3582
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8734 - loss: 0.3032 - val_accuracy: 0.8444 - val_loss: 0.3541
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8741 - loss: 0.3024 - val_accuracy: 0.8487 - val_loss: 0.3592
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8736 - loss: 0.3028 - val_accuracy: 0.8494 - val_loss: 0.3529
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8744 - loss: 0.3026 - val_accuracy: 0.8438 - val_loss: 0.3542
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8752 - loss: 0.3017 - val_accuracy: 0.8494 - val_loss: 0.3544
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8764 - loss: 0.3007 - val_accuracy: 0.8462 - val_loss: 0.3576
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8773 - loss: 0.3006 - val_accuracy: 0.8500 - val_loss: 0.3581
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8770 - loss: 0.3008 - val_accuracy: 0.8494 - val_loss: 0.3568
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8758 - loss: 0.3000 - val_accuracy: 0.8494 - val_loss: 0.3541
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8742 - loss: 0.2997 - val_accuracy: 0.8475 - val_loss: 0.3592
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8755 - loss: 0.2998 - val_accuracy: 0.8481 - val_loss: 0.3611
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8775 - loss: 0.2992 - val_accuracy: 0.8494 - val_loss: 0.3601
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8775 - loss: 0.2992 - val_accuracy: 0.8469 - val_loss: 0.3606
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8777 - loss: 0.2993 - val_accuracy: 0.8487 - val_loss: 0.3646
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8761 - loss: 0.2992 - val_accuracy: 0.8456 - val_loss: 0.3590
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8759 - loss: 0.2978 - val_accuracy: 0.8481 - val_loss: 0.3615
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8755 - loss: 0.2971 - val_accuracy: 0.8456 - val_loss: 0.3564
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8761 - loss: 0.2961 - val_accuracy: 0.8475 - val_loss: 0.3630
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8747 - loss: 0.2979 - val_accuracy: 0.8481 - val_loss: 0.3600
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8763 - loss: 0.2965 - val_accuracy: 0.8456 - val_loss: 0.3611
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8753 - loss: 0.2959 - val_accuracy: 0.8500 - val_loss: 0.3614
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8777 - loss: 0.2971 - val_accuracy: 0.8462 - val_loss: 0.3608
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8775 - loss: 0.2954 - val_accuracy: 0.8450 - val_loss: 0.3580
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8783 - loss: 0.2949 - val_accuracy: 0.8487 - val_loss: 0.3638
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8777 - loss: 0.2949 - val_accuracy: 0.8444 - val_loss: 0.3602
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8767 - loss: 0.2948 - val_accuracy: 0.8469 - val_loss: 0.3671
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8755 - loss: 0.2954 - val_accuracy: 0.8469 - val_loss: 0.3643
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8769 - loss: 0.2951 - val_accuracy: 0.8475 - val_loss: 0.3642
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8764 - loss: 0.2937 - val_accuracy: 0.8462 - val_loss: 0.3655
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8769 - loss: 0.2944 - val_accuracy: 0.8462 - val_loss: 0.3619
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8758 - loss: 0.2931 - val_accuracy: 0.8481 - val_loss: 0.3630
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8766 - loss: 0.2934 - val_accuracy: 0.8512 - val_loss: 0.3660
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8811 - loss: 0.2923 - val_accuracy: 0.8419 - val_loss: 0.3747
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8795 - loss: 0.2923 - val_accuracy: 0.8519 - val_loss: 0.3606
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8777 - loss: 0.2916 - val_accuracy: 0.8462 - val_loss: 0.3657
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8792 - loss: 0.2918 - val_accuracy: 0.8475 - val_loss: 0.3624
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8781 - loss: 0.2910 - val_accuracy: 0.8469 - val_loss: 0.3659
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8806 - loss: 0.2907 - val_accuracy: 0.8525 - val_loss: 0.3627
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8788 - loss: 0.2901 - val_accuracy: 0.8450 - val_loss: 0.3646
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8811 - loss: 0.2902 - val_accuracy: 0.8519 - val_loss: 0.3654
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8797 - loss: 0.2901 - val_accuracy: 0.8475 - val_loss: 0.3654
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8794 - loss: 0.2891 - val_accuracy: 0.8494 - val_loss: 0.3658
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8802 - loss: 0.2892 - val_accuracy: 0.8469 - val_loss: 0.3667
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8823 - loss: 0.2892 - val_accuracy: 0.8481 - val_loss: 0.3668
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8806 - loss: 0.2887 - val_accuracy: 0.8462 - val_loss: 0.3669
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8808 - loss: 0.2890 - val_accuracy: 0.8481 - val_loss: 0.3654
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8805 - loss: 0.2884 - val_accuracy: 0.8487 - val_loss: 0.3679
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8783 - loss: 0.2887 - val_accuracy: 0.8512 - val_loss: 0.3666
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8792 - loss: 0.2877 - val_accuracy: 0.8519 - val_loss: 0.3681

In [56]:
y_log = model.predict(x_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [57]:
np.where(y_log>0.5,1,0)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [60]:
from sklearn.metrics import accuracy_score
y_pred = np.where(y_log > 0.5, 1, 0)
accuracy_score(y_test, y_pred)

0.859